export BSPWM_TREE=/tmp/bspwm.tree
export BSPWM_HISTORY=/tmp/bspwm.history
export BSPWM_STACK=/tmp/bspwm.stack

# Enable esync for wine
export WINEESYNC=1

xrdb -merge -I$HOME ~/.Xresources
xset +fp ~/.fonts/
xset fp rehash
fc-cache -fv &
unclutter -root -visible -idle 5 -jitter 5 &
feh --bg-fill ~/.wall.jpg &
picom --config ~/.config/picom.conf &
batt mon &
sxhkd &
redshift &
dunst &
agenda remind 5 &

# for web highlighting
# maw ~/notes/annos/web/annos.jsonl ~/notes/annos/web/assets &

# Input selection
# Hit CTRL+SPACE+LEFT_SHIFT, in that order
# fcitx -d

# Properly set DBUS_SESSION_BUS_ADDRESS
source /etc/X11/Xsession.d/20dbus_xdg-runtime

# Auto-lock on idle
# Need to do `visudo` and add:
# username  ALL = NOPASSWD: /bin/systemctl suspend
xautolock -time 30 -locker "sudo systemctl suspend" -detectsleep &

# Bluetooth off by default
bt toggle

# Touchpad tweaks
DEVICE=$(xinput list | grep Synaptics | cut -f 2 | cut -f 2 -d=)
xinput --set-prop "$DEVICE" "Synaptics Noise Cancellation" 0 0
xinput --set-prop "$DEVICE" "Device Accel Profile" 6
xinput --set-prop "$DEVICE" "Device Accel Velocity Scaling" 50
xinput --set-prop "$DEVICE" "Device Accel Constant Deceleration" 12
xinput --set-prop "$DEVICE" "Synaptics Two-Finger Scrolling" 1 1
# Disable touchpad tapping/scrolling while typing, re-enable 0.5s after
syndaemon -t -i 0.5 &

# Trackpoint tweaks
DEVICE=$(xinput list | grep TrackPoint | cut -f 2 | cut -f 2 -d=)
xinput --set-prop "$DEVICE" "libinput Accel Speed" 0.1

# Fix for xdg-desktop-portal failing,
# causing slow GTK application start ups
# <https://github.com/swaywm/sway/issues/5732>
systemctl --user import-environment

exec ~/.config/bspwm/wm
