export BSPWM_TREE=/tmp/bspwm.tree
export BSPWM_HISTORY=/tmp/bspwm.history
export BSPWM_STACK=/tmp/bspwm.stack

xrdb -merge -I$HOME ~/.Xresources
xset +fp ~/.fonts/
xset fp rehash
fc-cache -fv &
unclutter -root -visible &
feh --bg-fill ~/.wallpaper.jpg &
battcheck &
sxhkd &
urxvt &
#mopidy &
monmon &
idle &
#compton -cb -o 0.4 -r 8 -l -8 -t -8 --unredir-if-possible &
exec ~/.config/bspwm/wm
