#! /bin/sh

NORMAL_BORDER_COLOR="#4e4e4e"
ACTIVE_BORDER_COLOR="#1a476b"
# FOCUSED_BORDER_COLOR="#43CC70"
FOCUSED_BORDER_COLOR="#d6c08f"

bspc config border_width        1
bspc config window_gap          0

# Automatically use monocle when only one window
bspc config single_monocle on

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      any
bspc config focus_follows_pointer false
bspc config pointer_modifier mod4 # super
bspc config pointer_action2 resize_side
bspc config normal_border_color "${NORMAL_BORDER_COLOR}"
bspc config active_border_color "${ACTIVE_BORDER_COLOR}"
bspc config focused_border_color "${FOCUSED_BORDER_COLOR}"

# Get a window name by running
# xprop | grep WM_CLASS
# and click on the window in question
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Gifview state=floating

for monitor in $(bspc query -M); do
    bspc monitor $monitor -n "$monitor" -d "∙" "∙" "∙"
done

# This must go after the rest of the config!
if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

panel &
