#!/bin/bash

source ~/.config/lemonbar/colors

CHARGE_ICON=""
PLUGGED_ICON=""

battery() {
    STATUS=$(acpi)
    TIME=$(echo $STATUS | grep -o '[0-9]*:[0-9]*:[0-9]*' | cut -d : -f 1,2)
    STATE=$(echo $STATUS | grep -o ': [^ ]*,' | tr -dc 'A-Za-z')
    PERCENT=$(echo $STATUS | grep -o '[^ ]*%' | tr -dc '0-9')

	if [[ $STATE == "Discharging" ]]; then
        if [ $PERCENT -lt 10 ]; then
            echo "%{F$COLOR_URGENT}${CHARGE_ICON}${TIME}%{F-}"
        else
            echo "%{F$COLOR_ICON}${CHARGE_ICON}%{F-}${TIME}"
        fi
    elif [ $PERCENT -lt 100 ]; then
        echo "%{F$COLOR_ICON}${PLUGGED_ICON}%{F-}${TIME}"
    else
        echo "%{F$COLOR_ICON}${PLUGGED_ICON}%{F-}"
    fi
}

while true; do
    echo 'B'$(battery)
    sleep 10
done
