#!/bin/bash

source ~/.config/lemonbar/colors

CHARGE_ICON=""
PLUGGED_ICON=""

battery() {
    BATTERY=$(upower -e | grep battery)

    TIME_RAW=$(upower -i $BATTERY | grep -E "to empty|to full" | cut -d':' -f2)
    TIME_NUMS=$(echo $TIME_RAW | cut -d' ' -f1)
    TIME_UNIT=$(echo $TIME_RAW | cut -d' ' -f2)

    if [[ $TIME_UNIT == "minute"* ]]; then
        TIME_UNIT="m"
    elif [[ $TIME_UNIT == "hour"* ]]; then
        TIME_UNIT="h"
    fi

    STATE=$(upower -i $BATTERY | grep "state" | cut -d':' -f2 | xargs)
    PERCENT=$(upower -i $BATTERY | grep "percent" | cut -d':' -f2 | tr -dc '0-9')
    TIME="${TIME_NUMS}${TIME_UNIT}"

	if [[ $STATE == "discharging" ]]; then
        if [ $PERCENT -lt 10 ]; then
            echo "%{F$COLOR_URGENT}${CHARGE_ICON}${TIME}%{F-}"
        else
            echo "%{F$COLOR_ICON}${CHARGE_ICON}%{F-}${TIME}"
        fi
    elif [ $PERCENT -lt 100 ]; then
        echo "%{F$COLOR_ICON}${PLUGGED_ICON}%{F-}${TIME}"
    else
        echo "%{F$COLOR_ICON}${PLUGGED_ICON}%{F-}"
    fi
}

while true; do
    echo 'B'$(battery)
    sleep 1s
done

