#!/bin/bash

source ~/.config/lemonbar/colors

btooth() {
    if [ "$(bluetooth)" == "bluetooth = on" ]; then
        ICON=""
    else
        ICON=""
    fi
    echo "%{F$COLOR_ICON}$ICON%{F-}"
}

while true; do
    echo 'L'$(btooth)
    sleep 5
done

