#!/bin/bash

source ~/.config/lemonbar/colors

caffeine() {
    if [ -f "/tmp/caffeine" ]; then
        ICON=""
    else
        ICON=""
    fi
    echo "%{F$COLOR_ICON}$ICON%{F-}"
}

while true; do
    echo 'F'$(caffeine)
    sleep 5
done

