#!/bin/bash
if [ $(pgrep -cx panel) -gt 1 ] ; then
    # pkill panel
    exit
fi
panel &

# xdotool listeners just stay listening rather than exiting,
# so we have to kill the old ones ourselves
listeners=$(pgrep -f 'xdotool search --sync --name wm_panel')
if [ ! -z "$listeners" ]; then
    echo -e "$listeners" | xargs kill
fi
xdotool search --sync --name "wm_panel" behave %@ mouse-leave exec pkill panel