#!/bin/bash

source ~/.config/lemonbar/colors

UPDATE_INTERVAL=5

IFACE=wlan0
H_ICON=""
M_ICON=""
L_ICON=""
VPN_CONFIG=/home/ftseng/docs/vpn/active/airvpn-ssl.ovpn

CHARGE_ICON=""
PLUGGED_ICON=""


wifi() {
    if [[ "$(/usr/bin/wifi)" == *"= on" ]]; then
        SSID=$(iwconfig $IFACE | sed -rn 's/.+ESSID:"(.+)"/\1/p')
        if [ -z "$SSID" ]; then
            TETHER=$(route | grep '^default' | grep -o '[^ ]*$' | grep -E 'enp0s20u2|usb0')
            if [ -z "$TETHER" ]; then
                status="offline"
            else
                status="TETHERED"
            fi
        else
            QUAL_RAW=$(iwconfig $IFACE | grep "Link Quality" | awk '{print $2}' | cut -d'=' -f2)
            QUAL_PERCENT=$(bc <<< "scale=2; ${QUAL_RAW}")

            if (( $(echo "$QUAL_PERCENT >= 0.9" | bc -l) )); then
                ICON=$H_ICON
            elif (( $(echo "$QUAL_PERCENT >= 0.6" | bc -l) )); then
                ICON=$M_ICON
            else
                ICON=$L_ICON
            fi
            status="${ICON}${SSID}"
        fi
    else
        status="off"
    fi

    # change bg based on vpn status
    bg=$COLOR_URGENT
    fg=$COLOR_BACKGROUND
    if pgrep openvpn > /dev/null; then
        # first check that openvpn is running,
        # then check that we are routed through the vpn gateway
        vpn_gateway=$(cat $VPN_CONFIG | grep net_gateway | cut -d' ' -f2)
        if route | grep -q $vpn_gateway; then
            bg="#43cc70"
            fg=$COLOR_FOREGROUND
        fi
    fi
    echo "%{B$bg}%{F$fg} ${status} %{F-}%{B-}"
}


volume() {
    STATUS=$(amixer -D pulse get -M Master)
    LEVEL=$(echo $STATUS | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
    STATE=$(echo $STATUS | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq)

    if [[ $STATE != "on" ]]; then
        ICON=""
    elif [[ $LEVEL -lt 40 ]]; then
        ICON=""
    elif [[ $LEVEL == 0 ]]; then
        ICON=""
    else
        ICON=""
    fi
    echo "%{F$COLOR_ICON}$ICON%{F-}"
}


bluetooth() {
    if [[ "$(/usr/bin/bluetooth)" == *"= on" ]]; then
        ICON=" "
    else
        ICON=""
    fi
    echo "%{F$COLOR_ICON}$ICON%{F-}"
}


battery() {
    STATUS=$(acpi)
    TIME=$(echo $STATUS | grep -o '[0-9]*:[0-9]*:[0-9]*' | cut -d : -f 1,2)
    STATE=$(echo $STATUS | grep -o ': [^ ]*,' | tr -dc 'A-Za-z')
    PERCENT=$(echo $STATUS | grep -o '[^ ]*%' | tr -dc '0-9')

	if [[ $STATE == "Discharging" ]]; then
        if [ $PERCENT -lt 10 ]; then
            echo "%{F$COLOR_URGENT}${CHARGE_ICON}${TIME}%{F-}"
        else
            echo "%{F$COLOR_ICON}${CHARGE_ICON}%{F-}${TIME}"
        fi
    elif [ $PERCENT -lt 100 ]; then
        echo "%{F$COLOR_ICON}${PLUGGED_ICON}%{F-}${TIME}"
    else
        echo "%{F$COLOR_ICON}${PLUGGED_ICON}%{F-}"
    fi
}


weather() {
    cat /tmp/weather
}


while true; do
    echo 'S'$(battery) $(volume)$(bluetooth) $(weather) $(wifi)
    sleep $UPDATE_INTERVAL
done
