#!/bin/bash

source ~/.config/lemonbar/colors

UPDATE_INTERVAL=3

IFACE=wlan0
H_ICON="~ "
M_ICON="- "
L_ICON="_ "
VPN_CONFIG=/home/ftseng/docs/vpn/active/airvpn-ssl.ovpn

CHARGE_ICON="BAT"
PLUGGED_ICON="AC"


wifi() {
    if [[ "$(/usr/bin/wifi)" == *"= on" ]]; then
        SSID=$(iwconfig $IFACE | sed -rn 's/.+ESSID:"(.+)"/\1/p')
        if [ -z "$SSID" ]; then
            TETHER=$(route | grep '^default' | grep -o '[^ ]*$' | grep -E 'enp0s20u2|usb0')
            if [ -z "$TETHER" ]; then
                status="offline"
            else
                status="TETHERED"
            fi
        else
            QUAL_RAW=$(iwconfig $IFACE | grep "Link Quality" | awk '{print $2}' | cut -d'=' -f2)
            QUAL_PERCENT=$(bc <<< "scale=2; ${QUAL_RAW}")

            if (( $(echo "$QUAL_PERCENT >= 0.9" | bc -l) )); then
                ICON=$H_ICON
            elif (( $(echo "$QUAL_PERCENT >= 0.6" | bc -l) )); then
                ICON=$M_ICON
            else
                ICON=$L_ICON
            fi
            status="${ICON}${SSID}"
        fi
    else
        status="off"
    fi

    # change bg based on vpn status
    bg=$COLOR_URGENT
    fg=$COLOR_BACKGROUND
    if pgrep openvpn > /dev/null; then
        # first check that openvpn is running,
        # then check that we are routed through the vpn gateway
        vpn_gateway=$(cat $VPN_CONFIG | grep net_gateway | cut -d' ' -f2)
        if route | grep -q $vpn_gateway; then
            bg="#43cc70"
            fg=$COLOR_FOREGROUND
        fi
    fi
    echo "%{B$bg}%{F$fg} ${status} %{F-}%{B-}"
}


volume() {
    STATUS=$(amixer -D pulse get -M Master)
    LEVEL=$(echo $STATUS | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
    STATE=$(echo $STATUS | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq)

    if [[ $STATE != "on" ]]; then
        ICON="MUTE"
    else
        ICON="V$LEVEL"
    fi
    echo "%{B$COLOR_ICON} $ICON %{B-}"
}


bluetooth() {
    if [[ "$(/usr/bin/bluetooth)" == *"= on" ]]; then
        ICON="B"
    else
        ICON=""
    fi
    echo "$ICON"
}


battery() {
    PERCENT=$(batt percent)

    if [[ $(batt status) = *"Discharging"* ]]; then
        if [ $PERCENT -lt 10 ]; then
            echo "%{B$COLOR_URGENT} |::: %{B-}"
        elif [ $PERCENT -lt 50 ]; then
            echo "%{B$COLOR_FOREGROUND}%{F$COLOR_BACKGROUND} ||:: %{F-}%{B-}"
        elif [ $PERCENT -lt 75 ]; then
            echo "%{B$COLOR_FOREGROUND}%{F$COLOR_BACKGROUND} |||: %{F-}%{B-}"
        else
            echo "%{B$COLOR_FOREGROUND}%{F$COLOR_BACKGROUND} |||| %{F-}%{B-}"
        fi
    else
        echo "${PLUGGED_ICON}:${PERCENT}% "
    fi
}

caffeine() {
    if [[ "$(xset q | grep "DPMS is")" == *"Disabled" ]]; then
        ICON="C"
    else
        ICON=""
    fi
    echo "$ICON"
}

email() {
    INBOX=$(notmuch count "folder:INBOX")
    UNREAD=$(notmuch count "tag:unread AND folder:INBOX")
    if (( $UNREAD > 0 )); then
        bg=$COLOR_ICON
    else
        bg="#cccccc"
    fi
    echo "%{B$bg} ${INBOX} %{B-}"
}

notifications() {
    if [ -f /tmp/dunst_paused ]; then
        echo "S"
    else
        echo ""
    fi
}

while true; do
    echo 'S'$(notifications)$(bluetooth)$(caffeine) $(battery)$(email)$(volume)$(wifi)
    sleep $UPDATE_INTERVAL
done
