#!/bin/bash

source ~/.config/lemonbar/colors

volume() {
    LEVEL=`amixer -D pulse get -M Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq`
    STATE=`amixer -D pulse get -M Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq`

    if [[ $STATE != "on" ]]; then
        ICON=""
    elif [[ $LEVEL -lt 40 ]]; then
        ICON=""
    elif [[ $LEVEL == 0 ]]; then
        ICON=""
    else
        ICON=""
    fi
    echo "%{F$COLOR_ICON}$ICON%{F-}"
}

while true; do
    echo 'V'$(volume)
    sleep 1s
done
