#!/bin/bash

source ~/.config/lemonbar/colors

volume() {
    STATUS=$(amixer -D pulse get -M Master)
    LEVEL=$(echo $STATUS | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
    STATE=$(echo $STATUS | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq)

    if [[ $STATE != "on" ]]; then
        ICON=""
    elif [[ $LEVEL -lt 40 ]]; then
        ICON=""
    elif [[ $LEVEL == 0 ]]; then
        ICON=""
    else
        ICON=""
    fi
    echo "%{F$COLOR_ICON}$ICON%{F-}"
}

while true; do
    echo 'V'$(volume)
    sleep 2
done
