#!/bin/bash

weather() {
    # b/c vpn messes with IP,
    # check for hardcoded coords first
    if [ -z "$LAT" ] || [ -z "$LNG" ] ; then
        IP=$(wget http://ipinfo.io/ip -qO -)
        RESP=$(curl -s https://freegeoip.net/json/${IP})
        LAT=$(echo "$RESP" | jq -r '{latitude} | .[]')
        LNG=$(echo "$RESP" | jq -r '{longitude} | .[]')
    fi

    TEMP=$(curl -s "api.openweathermap.org/data/2.5/weather?lat=${LAT}&lon=${LNG}&units=metric&APPID=95f3713bae74f740f00b0c3483916b40" | jq -r '{temp: .main.temp} | .[]')
    if [ -z $TEMP ]; then
        TEMP=?
    else
        # round to int
        TEMP=$(printf "%.0f" $TEMP)
    fi
    echo "${TEMP}°c"
}

while true; do
    echo 'R'$(weather)
    sleep 300s # every 5min
done
