#!/bin/bash

source ~/.config/lemonbar/colors

IFACE=wlan0
H_ICON=""
M_ICON=""
L_ICON=""
VPN_CONFIG=/home/ftseng/docs/vpn/active/airvpn-ssl.ovpn

wifi() {
    SSID=$(iwconfig $IFACE | sed -rn 's/.+ESSID:"(.+)"/\1/p')
	if [ -z "$SSID" ]; then
		status="offline"
	else
        QUAL_RAW=$(iwconfig $IFACE | grep "Link Quality" | awk '{print $2}' | cut -d'=' -f2)
        QUAL_PERCENT=$(bc <<< "scale=2; ${QUAL_RAW}")

        if (( $(echo "$QUAL_PERCENT >= 0.9" | bc -l) )); then
            ICON=$H_ICON
        elif (( $(echo "$QUAL_PERCENT >= 0.6" | bc -l) )); then
            ICON=$M_ICON
        else
            ICON=$L_ICON
        fi
        status="${ICON}${SSID}"
	fi

    # change bg based on vpn status
    bg=$COLOR_URGENT
    fg=$COLOR_BACKGROUND
    if pgrep openvpn > /dev/null; then
        # first check that openvpn is running,
        # then check that we are routed through the vpn gateway
        vpn_gateway=$(cat $VPN_CONFIG | grep net_gateway | cut -d' ' -f2)
        if route | grep -q $vpn_gateway; then
            bg="#43cc70"
            fg=$COLOR_FOREGROUND
        fi
    fi
    echo "%{B$bg}%{F$fg} ${status} %{F-}%{B-}"
}

while true; do
    echo 'N'$(wifi)
    sleep 1s
done
