#!/bin/bash
# <https://github.com/AckslD/Qute-Translate>

while [[ $# > 0 ]]; do
    case $1 in
        -s|--source)
            QUTE_TRANS_SOURCE=$2
            shift
            shift
            ;;
        -t|--target)
            QUTE_TRANS_TARGET=$2
            shift
            shift
            ;;
    esac
done

if [[ -z $QUTE_TRANS_SOURCE ]]; then
    # Default use automatic language for source
    QUTE_TRANS_SOURCE="auto"
fi
if [[ -z $QUTE_TRANS_TARGET ]]; then
    # Default use English for target
    QUTE_TRANS_TARGET="en"
fi

# Translate selected text
PAGE="https://translate.google.com/#view=home&op=translate&"
CONT_KEY="text"
CONTENT=$QUTE_SELECTED_TEXT

echo "open -t ${PAGE}sl=$QUTE_TRANS_SOURCE&tl=$QUTE_TRANS_TARGET&$CONT_KEY=$CONTENT" >> "$QUTE_FIFO"
