export GPG_TTY=$(tty)

export XKB_DEFAULT_OPTIONS=caps:super,compose:ralt,compose:rctrl
export BEMENU_OPTS='-i --fn "Source Code Pro Light 9" -l 10 --hf "#598DDC" --tf "#079875" --cw 1'
export MOZ_ENABLE_WAYLAND=1

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
for file in ~/.dippindots/dots/bash/{path,prompt,aliases,functions,keys}; do
	[ -r "$file" ] && source "$file"
done
unset file

eval "$(zoxide init bash)"

# pyenv
eval "$(pyenv init --path)"

# fnm
export PATH="/home/ftseng/.local/share/fnm:$PATH"
eval "`fnm env`"
