export GPG_TTY=$(tty)

# Add yabridge
# export PATH="$PATH:$HOME/.local/share/yabridge"

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
for file in ~/.dippindots/dots/bash/{path,prompt,aliases,functions,keys}; do
	[ -r "$file" ] && source "$file"
done
unset file

# pyenv
# eval "$(pyenv init --path)"

# fnm
# export PATH="/home/ftseng/.local/share/fnm:$PATH"
# eval "`fnm env`"
