# Load env values.
source /etc/environment

# 256 color term.
export TERM=screen-256color-s

# Make vim the default editor
export EDITOR="vim"
export VISUAL="vim"

# Larger bash history
export HISTSIZE=10000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL="ignoreboth:erasedups"
export HISTIGNORE="ls:cd:pwd:exit:date:* --help:za *:\
                   kill *:pkill *:aa *:ps *:..:dl:h:which *:man *:\
                   gcm *:gp:ga *:gcm *:\
                   ipython:python:python3"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null
done

# vi keybindings for bash
set -o vi

# Setup pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
# eval "$(pyenv init --path)"

# Setup GDAL for GIS stuff
export GDAL_DATA=/usr/share/gdal

[[ -r ~/.bashrc ]] && . ~/.bashrc

source /home/ftseng/.config/broot/launcher/bash/br
