# Load env values.
source /etc/environment

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.dippindots/dots/bash/{path,prompt,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# So tmux uses proper vim colors.
export TERM=screen-256color

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Ignore less interesting commands in the history
export HISTIGNORE=*history*:ls:ll:la:cd:pwd:gpg:exit:su:df:clear

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null
done

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion

# vi keybindings for bash
set -o vi

# initialize fasd
eval "$(fasd --init auto)"

# initialize fzf
# set to ag, which will respect gitignores
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_CTRL_T_COMMAND="fd . $HOME"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"

# rvm
# source ~/.rvm/scripts/rvm
